# Generated by Django 2.2.16 on 2022-11-30 15:33

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20221126_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.TextField(validators=[recipes.validators.validate_max_size_text], verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.TextField(validators=[recipes.validators.validate_max_size_text], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.TextField(validators=[recipes.validators.validate_max_size_text], verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(validators=[recipes.validators.validate_max_size_text], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ManyToManyField(related_name='recipes', to='recipes.Recipe', verbose_name='Рецепты'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.TextField(default='#ffffff', unique=True, validators=[recipes.validators.validate_is_hex], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(unique=True, validators=[recipes.validators.validate_max_size_text], verbose_name='Название тега'),
        ),
    ]
