# Generated by Django 2.2.16 on 2022-11-30 12:52

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20221129_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.TextField(validators=[recipes.validators.validate_max_size_text], verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.TextField(validators=[recipes.validators.validate_max_size_text], verbose_name='Название'),
        ),
    ]
