# Generated by Django 2.2.16 on 2022-11-30 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221130_1533'),
        ('users', '0003_auto_20221130_1252'),
    ]

    operations = [
    ]
